[2022-12-13 16:06:03]<16560><INFO> 	Init Log Complete
[2022-12-13 16:06:03]<16560><INFO> 	======================
[2022-12-13 16:06:03]<16560><INFO> 	Program Init
[2022-12-13 16:06:03]<16560><INFO> 	Config Path: TASK_2/genData.json
[2022-12-13 16:06:03]<16560><CRITICAL> 	Exception Occurs!
[2022-12-13 16:06:03]<16560><CRITICAL> 	'NoneType' object has no attribute 'genType'
[2022-12-13 16:06:03]<16560><CRITICAL> 	Traceback (most recent call last):
  File "E:\MyCode_Data\paper_chi\revisiting_daniel\util\shareCode.py", line 25, in globalCatch
    funcName()
  File "GenDataset.py", line 105, in main
    gener=GenDataset(config)
  File "GenDataset.py", line 35, in __init__
    modelName = "Dataset.%s.%s"%(config.data.generator.genType,config.data.generator.genType)
AttributeError: 'NoneType' object has no attribute 'genType'

